---

- name: Reset Kubernetes
  shell: "kubeadm reset --force"

- name: Join the Kubernetes cluster
  shell: |
    kubeadm join --skip-phases=preflight \
                 --token {{ token }} \
                 192.168.122.200:6443 \
                 --discovery-token-unsafe-skip-ca-verification

- name: Reload and restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
